/* scripts/build-network.mjs
   Regenerates server/routes-data.js for Xperion Airways as a US-based global
   carrier. Source: OurAirports public dataset (ourairports.com, public domain),
   fetched at build time; the generated file is committed so runtime needs no
   network. Selection: every large airport worldwide with scheduled service and
   an IATA code, plus medium airports to guarantee coverage of 150+ countries,
   the top international cities, and broad US domestic coverage.
   Topology: hub-and-spoke from MIA + JFK to every served airport, plus a full
   mesh across US focus cities. Any other pair still works: the search engine
   synthesizes unlisted routes on demand. Run: node scripts/build-network.mjs */
import fs from "node:fs";

const SRC = "https://raw.githubusercontent.com/davidmegginson/ourairports-data/main/airports.csv";
const HUBS = ["MIA", "JFK"];
const FOCUS = ["ORD","LAX","DFW","SFO","SEA","ATL","DEN","BOS","IAH","PHX","LAS","MCO","SLC","CLT","MSP","DTW"];
const MIDDLE_EAST = new Set(["AE","SA","QA","OM","KW","BH","IL","JO","LB","IQ","IR","YE","SY"]);
const REGION = { NA: "North America", SA: "South America", EU: "Europe", AF: "Africa", AS: "Asia", OC: "Oceania" };

function parseCsv(text) {
  const rows = []; let row = [], cell = "", q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) { if (c === '"') { if (text[i + 1] === '"') { cell += '"'; i++; } else q = false; } else cell += c; }
    else if (c === '"') q = true;
    else if (c === ",") { row.push(cell); cell = ""; }
    else if (c === "\n") { row.push(cell); rows.push(row); row = []; cell = ""; }
    else if (c !== "\r") cell += c;
  }
  if (cell || row.length) { row.push(cell); rows.push(row); }
  return rows;
}

const csv = await (await fetch(SRC)).text();
const [head, ...rows] = parseCsv(csv);
const col = Object.fromEntries(head.map((h, i) => [h, i]));
const all = rows
  .filter(r => r.length > col.iata_code)
  .map(r => ({
    type: r[col.type], iata: r[col.iata_code], name: r[col.name],
    city: (r[col.municipality] || r[col.name]).replace(/\s*\(.*?\)\s*/g, " ").trim() || r[col.name].replace(/ (International|Intl|Regional|Municipal)? ?Airport.*$/i, ""),
    cc: r[col.iso_country], region: MIDDLE_EAST.has(r[col.iso_country]) ? "Middle East" : (REGION[r[col.continent]] || "Asia"),
    scheduled: r[col.scheduled_service] === "yes",
  }))
  .filter(a => a.iata && /^[A-Z]{3}$/.test(a.iata) && a.scheduled);

const large = all.filter(a => a.type === "large_airport");
const medium = all.filter(a => a.type === "medium_airport");

const picked = new Map();
const add = (a) => { if (!picked.has(a.iata)) picked.set(a.iata, a); };

large.forEach(add);                                            // every large airport worldwide
medium.filter(a => a.cc === "US").forEach(add);                // near-complete US domestic coverage
const have = () => new Set([...picked.values()].map(a => a.cc));
for (const a of medium) if (!have().has(a.cc)) add(a);         // one airport minimum per remaining country
for (const a of medium) { if (picked.size >= 1500) break; add(a); }   // fill toward ~1000 intl cities

// make sure every code the app references is present
const MUST = ["MIA","JFK","LIS","OPO","CUN","LAS","SJU","NAS","DEL","MCO","FLL","ATL","JAI","AMD","OSL","CPH","ARN","HEL","FRA","LHR","GRU","MAD","CDG","FAO","FNC"];
for (const m of MUST) if (!picked.has(m)) { const a = all.find(x => x.iata === m); if (a) add(a); }

const airports = [...picked.values()].sort((x, y) => x.iata.localeCompare(y.iata));
const countries = new Set(airports.map(a => a.cc));
const usCount = airports.filter(a => a.cc === "US").length;

const esc = (s) => String(s).replace(/\\/g, "").replace(/"/g, '\\"');
const lines = airports.map(a => `  ${a.iata}: { city: "${esc(a.city)}", country: "${esc(a.cc)}", region: "${a.region}" },`);

const routes = [];
for (const a of airports) for (const h of HUBS) if (a.iata !== h) routes.push([h, a.iata]);
for (let i = 0; i < FOCUS.length; i++) for (let j = i + 1; j < FOCUS.length; j++) routes.push([FOCUS[i], FOCUS[j]]);

const out = `/* ──────────────────────────────────────────────────────────────
   Xperion Airways — route network (GENERATED by scripts/build-network.mjs)
   US-based global carrier. Hubs: Miami (MIA) + New York JFK.
   ${airports.length} served airports · ${countries.size} countries · ${usCount} US cities.
   Source: OurAirports public-domain dataset. Every large airport with
   scheduled service worldwide, plus medium airports for full country and
   US-domestic coverage. Routes below are the published hub-and-spoke and
   US focus-city mesh; the search engine synthesizes any other served pair
   on demand, so every city here is bookable to every other.
   ────────────────────────────────────────────────────────────── */

const AIRPORTS = {
${lines.join("\n")}
};

const BASE_ROUTES = ${JSON.stringify(routes)};

// Deterministic timings/fares per leg, same formula as the search engine's
// on-demand synthesizer, so published and synthesized routes feel identical.
const REGION_MIN = {
  "Europe|Europe": 120, "North America|North America": 300, "South America|South America": 180,
  "Africa|Africa": 200, "Asia|Asia": 240, "Middle East|Middle East": 120,
  "Africa|Europe": 330, "Europe|Middle East": 330, "Asia|Europe": 690,
  "Europe|South America": 630, "Europe|North America": 480, "Africa|Middle East": 300,
  "Africa|North America": 660, "Africa|South America": 600, "Africa|Asia": 600,
  "Middle East|North America": 720, "Middle East|South America": 780, "Asia|Middle East": 420,
  "Asia|North America": 720, "North America|South America": 510, "Asia|South America": 900,
  "Oceania|Oceania": 240, "Asia|Oceania": 540, "North America|Oceania": 780,
  "Europe|Oceania": 1260, "South America|Oceania": 780, "Africa|Oceania": 840, "Middle East|Oceania": 840,
};
const legOf = (o, d) => {
  const A = AIRPORTS[o], B = AIRPORTS[d];
  const base = REGION_MIN[[A.region, B.region].sort().join("|")] || 240;
  let h = 0; for (const c of o + d) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  const dur = Math.round(base * (0.85 + (h % 30) / 100));
  return [o, d, dur, Math.max(55, Math.round(dur * 0.86))];
};

const ROUTES = (() => {
  const seen = new Set(); const out = [];
  for (const [a, b] of BASE_ROUTES) {
    for (const [o, d] of [[a, b], [b, a]]) {
      const k = o + "-" + d;
      if (!seen.has(k) && AIRPORTS[o] && AIRPORTS[d] && o !== d) { seen.add(k); out.push(legOf(o, d)); }
    }
  }
  return out;
})();

module.exports = { AIRPORTS, ROUTES };
`;
fs.writeFileSync("server/routes-data.js", out);
console.log(`written server/routes-data.js: ${airports.length} airports, ${countries.size} countries, ${usCount} US, ${routes.length * 2} route legs`);
